#!/bin/bash
##===================================================================##
 # SPDX-License-Identifier: GPL-3.0-or-later                         #
 # Copyright (c) 2025 Jimmy Källhagen                                #
 # Part of Yggdrasil - Nordix desktop environment                    #
 # Nordix and Yggdrasil are registered trademarks of Jimmy Källhagen # 
##===================================================================##


cores=$(($(nproc) / 2))
for ((i=0; i<cores; i++)); do
    printf "Core %2d:  %2d - %2d\n" "$i" "$i" "$((i + cores))"
done
